Improve code quality

diff --git a/arch-linux-desktop-installation b/arch-linux-desktop-installation
--- a/arch-linux-desktop-installation
+++ b/arch-linux-desktop-installation
@@ -1,10 +1,17 @@
 #!/bin/bash
 
-# Installation script for i3 desktop environment.
+# Installation script for Arch Linux desktop environment.
 
-if ! sudo true; then
+error() {
+  printf "%s\n" "Failed to install Arch Linux desktop environment" >&2
   exit 1
-fi
+}
+
+set -Ee -o pipefail
+
+trap error ERR
+
+sudo --validate
 
 readonly -A COLORS=(
   ["Gray A"]="#282828"
@@ -26,16 +33,14 @@ if whiptail --title "Logging" --yesno "Enable logging?" "${DEFAULT_HEIGHT}" "${D
   exec &> >(tee --append "${BASH_SOURCE[0]}.log")
 fi
 
-set -xue
+set -ux
 
-trap 'printf "%s\n" "Failed to install i3 desktop environment"' ERR
-
+sudo mkdir --parents /etc/pacman.d/conf/
 sudo tee /etc/pacman.d/conf/noto-fonts <<- EOF
 	NoExtract = usr/share/fonts/noto/Noto*.ttf
 	NoExtract = !usr/share/fonts/noto/NotoColorEmoji.ttf
 	NoExtract = !usr/share/fonts/noto/NotoSans-*.ttf
 	NoExtract = !usr/share/fonts/noto/NotoSansMono-*.ttf
-	NoExtract = !usr/share/fonts/noto/NotoSansSymbols
 	NoExtract = !usr/share/fonts/noto/NotoSansSymbols-*.ttf
 	NoExtract = !usr/share/fonts/noto/NotoSerif-*.ttf
 EOF
@@ -137,27 +142,28 @@ readonly packages
 sudo pacman --noconfirm --sync --refresh "${packages[@]}"
 
 readonly arc_theme_version="20221218"
-readonly arc_theme_directory="$(mktemp -d)"
+arc_theme_directory="$(mktemp -d)"; readonly arc_theme_directory
 sudo pacman --noconfirm --sync meson sassc
 wget --directory-prefix "${arc_theme_directory}/" "https://github.com/kontextwechsel/arc-theme/releases/download/${arc_theme_version}/arc-theme-${arc_theme_version}.tar.xz"
 tar --extract --file "${arc_theme_directory}/arc-theme-${arc_theme_version}.tar.xz" --directory "${arc_theme_directory}/"
 meson setup --prefix="${arc_theme_directory}/arc-theme-${arc_theme_version}/install/" -Dthemes=gtk3,gtk4 -Dvariants=lighter -Dtransparency=false "${arc_theme_directory}/arc-theme-${arc_theme_version}/build/" "${arc_theme_directory}/arc-theme-${arc_theme_version}/"
 meson install -C "${arc_theme_directory}/arc-theme-${arc_theme_version}/build/"
-sudo cp --recursive "${arc_theme_directory}/arc-theme-${arc_theme_version}/install/share/themes/Arc-Lighter-solid/" /usr/share/themes/Arc/
+sudo mkdir --parents /usr/share/themes/Arc/
+sudo cp --recursive "${arc_theme_directory}/arc-theme-${arc_theme_version}/install/share/themes/Arc-Lighter-solid/"* /usr/share/themes/Arc/
 sudo sed --in-place "s/Arc-Lighter-solid/Arc/g" /usr/share/themes/Arc/index.theme
 sudo chmod --recursive u=rwX,go=rX /usr/share/themes/Arc/
-sudo pacman --noconfirm --remove meson sassc
+sudo pacman --noconfirm --remove --recursive meson sassc
 rm --recursive "${arc_theme_directory:?}/"
 
 readonly arc_icon_theme_version="20161122"
-readonly arc_icon_theme_directory="$(mktemp -d)"
+arc_icon_theme_directory="$(mktemp -d)"; readonly arc_icon_theme_directory
 wget --directory-prefix "${arc_icon_theme_directory}/" "https://github.com/kontextwechsel/arc-icon-theme/archive/refs/tags/${arc_icon_theme_version}.tar.gz"
 tar --extract --file "${arc_icon_theme_directory}/${arc_icon_theme_version}.tar.gz" --directory "${arc_icon_theme_directory}/"
 sudo cp --recursive "${arc_icon_theme_directory}/arc-icon-theme-${arc_icon_theme_version}/Arc/" /usr/share/icons/
 sudo mkdir --parents /usr/share/icons/Arc/symbolic/legacy/
-sudo find /usr/share/icons/Arc/ -name applications-system.png -execdir ln -s {} gtk-preferences.png \; # GPicView requirement
-sudo find /usr/share/icons/Arc/ -name folder.png -execdir ln -s -f -n {} application-menu.png \; # FeatherPad requirement
-sudo find /usr/share/icons/Arc/ -name view-list-details-symbolic.png -execdir ln -s {} sidebar-expand-left.png \; # FeatherPad requirement
+sudo find /usr/share/icons/Arc/ -name applications-system.png -execdir ln --symbolic --force {} gtk-preferences.png \; # GPicView requirement
+sudo find /usr/share/icons/Arc/ -name folder.png -execdir ln --symbolic --force {} application-menu.png \; # FeatherPad requirement
+sudo find /usr/share/icons/Arc/ -name view-list-details-symbolic.png -execdir ln --symbolic --force {} sidebar-expand-left.png \; # FeatherPad requirement
 sudo chmod --recursive u=rwX,go=rX /usr/share/icons/Arc/
 rm --recursive "${arc_icon_theme_directory:?}/"
 
@@ -174,7 +180,7 @@ sudo tee /usr/local/bin/application-launcher <<- EOF
 	  done < "\${file}"
 	fi
 
-	function print() {
+	print_applications() {
 	  case "\$1" in
 	    -k | --keys)
 	      printf "%s\n" "\${!applications[@]}" | sort
@@ -205,7 +211,7 @@ sudo tee /usr/local/bin/application-launcher <<- EOF
 	      else
 	          applications["\$2"]="\${executable/#\${HOME}/\~} \${*:4}"
 	      fi
-	      print > "\${file}"
+	      print_applications > "\${file}"
 	      ;;
 	    -r | --remove)
 	      if [[ -z "\${applications["\$2"]+application}" ]]; then
@@ -213,10 +219,10 @@ sudo tee /usr/local/bin/application-launcher <<- EOF
 	        exit 1
 	      fi
 	      unset applications["\$2"]
-	      print > "\${file}"
+	      print_applications > "\${file}"
 	      ;;
 	    -l | --list)
-	      print | column --table --separator "="
+	      print_applications | column --table --separator "="
 	      ;;
 	    *)
 	      printf "Usage: %s [--add|--remove|--list] [APPLICATION] [EXECUTABLE] [ARGUMENTS...]\n" "\$(basename \${BASH_SOURCE[0]})"
@@ -225,7 +231,7 @@ sudo tee /usr/local/bin/application-launcher <<- EOF
 	  esac
 	else
 	  if [[ -n "\${DISPLAY}" ]]; then
-	    readonly selection="\$(dmenu -i -sb "${COLORS["Gray C"]}" <<< "\$(print --keys)")"
+	    readonly selection="\$(dmenu -i -sb "${COLORS["Gray C"]}" <<< "\$(print_applications --keys)")"
 	    if [[ -n "\${selection}" ]]; then
 	      i3-msg "exec --no-startup-id \${applications[\${selection}]}"
 	    fi
@@ -271,7 +277,7 @@ sudo tee /usr/local/bin/screenshot <<- EOF
 	        ;;
 	      -c | --clipboard)
 	        filename="\$(mktemp --suffix=".png")"
-	        trap "{ xclip -selection clipboard -target image/png -in \${filename}; rm -rf \${filename}; }" EXIT
+	        trap "{ xclip -selection clipboard -target image/png -in \${filename}; rm -f \${filename}; }" EXIT
 	        shift
 	        ;;
 	      *)
@@ -292,7 +298,7 @@ sudo chmod +x /usr/local/bin/screenshot
 
 sudo mkdir --parents /usr/local/share/bash-completion/completions/
 sudo tee /usr/local/share/bash-completion/completions/application-launcher <<-EOF
-	function _application-launcher() {
+	_application-launcher() {
 	  if [[ "\${COMP_CWORD}" -eq 1 ]]; then
 	    for option in \$(compgen -W "--add --remove --list" -- "\${COMP_WORDS["\${COMP_CWORD}"]}"); do
 	      COMPREPLY+=("\${option} ")
@@ -331,7 +337,7 @@ sudo tee /usr/local/share/bash-completion/completions/display-configuration <<- 
 	complete display-configuration
 EOF
 sudo tee /usr/local/share/bash-completion/completions/screenshot <<- EOF
-	function _screenshot() {
+	_screenshot() {
 	  readarray -t COMPREPLY < <(compgen -W "--clipboard --select" -- "\${COMP_WORDS["\${COMP_CWORD}"]}")
 	}
 	complete -F _screenshot screenshot
@@ -435,10 +441,9 @@ sudo tee /etc/skel/.bashrc <<- EOF
 	  shopt -s histappend
 	  tabs 4
 
-	  eval "\$(dircolors -b)"
+	  eval "\$(dircolors --bourne-shell)"
 
-	  pgrep -u "\${USER}" ssh-agent > /dev/null
-	  if [[ "\$?" -ne 0 ]]; then
+	  if ! pgrep --euid "\$(id --user)" ssh-agent > /dev/null; then
 	    ssh-agent -s > "\${HOME}/.sshrc"
 	  fi
 	  source "\${HOME}/.sshrc" > /dev/null
@@ -452,7 +457,7 @@ sudo tee /etc/skel/.bashrc <<- EOF
 	  alias bc="/usr/bin/bc --mathlib"
 	  alias cal="/usr/bin/cal --months 9 --span"
 
-	  function toggle_history() {
+	toggle_history() {
 	    if [[ -z "\${HISTFILE:+substitution}" ]]; then
 	      HISTFILE="\${HOME}/.bash_history"
 	      printf "\e[30mHistory enabled\e[0m\n"
@@ -463,7 +468,7 @@ sudo tee /etc/skel/.bashrc <<- EOF
 	  }
 	  bind -x '"\eh": toggle_history'
 
-	  function prettify_git() {
+	prettify_git() {
 	    args=("\$@")
 	    case "\$1" in
 	      log)
@@ -742,7 +747,7 @@ sudo tee /etc/skel/.config/i3.d/20-display <<- EOF
 EOF
 sudo tee /etc/skel/.config/i3.d/30-status <<- EOF
 	bar {
-	    status_command i3status -c "/run/user/\${UID}/i3status/config"
+	    status_command i3status --config "/run/user/\${UID}/i3status/config"
 	    position bottom
 	    strip_workspace_numbers yes
 
@@ -810,23 +815,25 @@ sudo tee /etc/skel/.config/i3status.d/30-disk <<- EOF
 	    format = "%free"
 	}
 EOF
-readonly interface="$(ip -brief link show | awk '$2 == "UP" { print $1; exit }')"
-if [[ "${interface}" == w* ]]; then
-  sudo tee /etc/skel/.config/i3status.d/60-wlan <<- EOF
-		order += "wireless ${interface}"
-		wireless ${interface} {
-		    format_up = "%essid"
-		    format_down = "—"
-		}
-	EOF
-else
-  sudo tee /etc/skel/.config/i3status.d/70-ethernet <<- EOF
-		order += "ethernet ${interface}"
-		ethernet ${interface} {
-		    format_up = "%ip"
-		    format_down = "—"
-		}
-	EOF
+interface="$(ip -brief link show | awk '$2 == "UP" { print $1; exit }')"; readonly interface
+if [[ -n "${interface}" ]]; then
+  if [[ "${interface}" == w* ]]; then
+    sudo tee /etc/skel/.config/i3status.d/60-wlan <<- EOF
+			order += "wireless ${interface}"
+			wireless ${interface} {
+			    format_up = "%essid"
+			    format_down = "—"
+			}
+		EOF
+  else
+    sudo tee /etc/skel/.config/i3status.d/70-ethernet <<- EOF
+			order += "ethernet ${interface}"
+			ethernet ${interface} {
+			    format_up = "%ip"
+			    format_down = "—"
+			}
+		EOF
+  fi
 fi
 sudo tee /etc/skel/.config/i3status.d/90-time <<- EOF
 	order += "tztime local"
@@ -1022,11 +1029,12 @@ sudo tee /etc/skel/.config/featherpad/fp.conf <<- EOF
 	sysIcons=true
 EOF
 
-readonly gimp_version="$(pacman -Q gimp | awk '{ print $2 }' | awk --field-separator "." '{ print $1 "." $2 }')"
+gimp_version="$(pacman --query gimp | awk '{ print $2 }' | awk --field-separator "." '{ print $1 "." $2 }')"; readonly gimp_version
 sudo mkdir --parents "/etc/skel/.config/GIMP/${gimp_version}/"
 sudo tee "/etc/skel/.config/GIMP/${gimp_version}/gimprc" <<- EOF
 	(theme "System")
 	(theme-color-scheme light)
+	(show-welcome-dialog no)
 EOF
 
 if [[ "$(< /sys/devices/virtual/dmi/id/sys_vendor)" == "QEMU" ]]; then
@@ -1034,7 +1042,7 @@ if [[ "$(< /sys/devices/virtual/dmi/id/sys_vendor)" == "QEMU" ]]; then
   sudo tee /etc/skel/.config/i3.d/21-spice <<- EOF
 		exec --no-startup-id spice-vdagent
 	EOF
-	sudo ln --symbolic /usr/bin/true /usr/local/bin/picom
+  sudo ln --symbolic /usr/bin/true /usr/local/bin/picom # Disable picom in QEMU environment
 fi
 
 rsync --recursive --links --verbose /etc/skel/ "${HOME}/"
diff --git a/arch-linux-installation b/arch-linux-installation
--- a/arch-linux-installation
+++ b/arch-linux-installation
@@ -2,12 +2,20 @@
 
 # Installation script for Arch Linux system.
 
-if [[ "${UID}" != 0 ]]; then
+error() {
+  printf "%s\n" "Failed to install Arch Linux system" >&2
   exit 1
+}
+
+set -Ee -o pipefail
+
+trap error ERR SIGUSR1
+
+if [[ "${EUID}" -ne 0 ]]; then
+  error
 fi
 
 readonly PROCESS_ID="$$"
-trap 'exit 1' SIGUSR1
 
 readonly DEFAULT_HEIGHT=7
 readonly DEFAULT_WIDTH=74
@@ -22,7 +30,7 @@ fi
 buffer=()
 while IFS= read -r disk; do
   if lsblk --noheadings --list --output MOUNTPOINT "${disk}" | awk 'length($1) != 0 { exit 1 }'; then
-    buffer+=("${disk}" "$(printf "%-${DEFAULT_PADDING}s" "${disk}")")
+    buffer+=("${disk}" "$(printf "%-*s" "${DEFAULT_PADDING}" "${disk}")")
     if (( "${#buffer[@]}" > 3 )); then
       buffer+=("OFF")
     else
@@ -34,14 +42,14 @@ if (( "${#buffer[@]}" == 0 )); then
   whiptail --title "Installation disk" --msgbox "No disk detected" "${DEFAULT_HEIGHT}" "${DEFAULT_WIDTH}"
   exit 1
 fi
-readonly disk="$(whiptail --title "Installation disk" --radiolist --notags "" "$(( "${DEFAULT_HEIGHT}" - 1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")"
+disk="$(whiptail --title "Installation disk" --radiolist --notags "" "$(( "${DEFAULT_HEIGHT}" - 1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")"; readonly disk
 
 buffer=()
 while IFS= read -r interface; do
   unset name
   case "${interface}" in
     e*)
-      # Use predictable network interface name for ethernet interfaces
+      # Use predictable network interface name for Ethernet interfaces
       if [[ -e "/sys/class/net/${interface}" ]]; then
         unset ID_NET_NAME_FROM_DATABASE ID_NET_NAME_ONBOARD ID_NET_NAME_SLOT ID_NET_NAME_PATH ID_NET_NAME_MAC
         source <(udevadm info --query=property --export "/sys/class/net/${interface}")
@@ -70,7 +78,7 @@ if (( "${#buffer[@]}" == 0 )); then
   whiptail --title "Network interface" --msgbox "No interface detected" "${DEFAULT_HEIGHT}" "${DEFAULT_WIDTH}"
   exit 1
 fi
-readonly interface="$(whiptail --title "Network interface" --radiolist --notags "" "$(( "${DEFAULT_HEIGHT}" - 1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")"
+interface="$(whiptail --title "Network interface" --radiolist --notags "" "$(( "${DEFAULT_HEIGHT}" - 1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")"; readonly interface
 
 unset hostname
 while true; do
@@ -135,7 +143,7 @@ buffer=(
   "us" "$(printf "%-${DEFAULT_PADDING}s" "English (ANSI)")" "ON"
   "de" "$(printf "%-${DEFAULT_PADDING}s" "German (ISO)")" "OFF"
 )
-readonly keymap="$(whiptail --title "Keyboard layout" --radiolist --notags "" "$(( "${DEFAULT_HEIGHT}" -1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")"
+keymap="$(whiptail --title "Keyboard layout" --radiolist --notags "" "$(( "${DEFAULT_HEIGHT}" -1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")"; readonly keymap
 
 if whiptail --title "SSH" --yesno "Enable SSH daemon?" "${DEFAULT_HEIGHT}" "${DEFAULT_WIDTH}" 3>&1 1>&2 2>&3; then
   readonly selection_enable_sshd="yes"
@@ -152,8 +160,9 @@ if [[ "${boot_mode}" == "uefi" ]]; then
 fi
 
 if [[ "${boot_mode}" == "uefi" ]]; then
+  selection_options=()
   if [[ "${selection_default_efi}" == "yes" ]]; then
-    readonly selection_options=("--defaultno")
+    selection_options+=("--defaultno")
   fi
   if whiptail --title "EFI" --yesno "Add EFI image to boot manager?" "${selection_options[@]}" "${DEFAULT_HEIGHT}" "${DEFAULT_WIDTH}" 3>&1 1>&2 2>&3; then
     readonly selection_boot_entry="yes"
@@ -170,17 +179,14 @@ else
   for firmware in "${available_firmwares[@]}"; do
     buffer+=("linux-firmware-${firmware}" "$(printf "%-${DEFAULT_PADDING}s" "linux-firmware-${firmware}")" "OFF")
   done
-  readarray -t selected_firmware_packages < <(whiptail --separate-output --title "Packages" --checklist --notags "" "$(( "${DEFAULT_HEIGHT}" -1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}")
+  readarray -t selected_firmware_packages < <(whiptail --separate-output --title "Packages" --checklist --notags "" "$(( "${DEFAULT_HEIGHT}" -1 + ${#buffer[@]} / 3 ))" "${DEFAULT_WIDTH}" "$(( ${#buffer[@]} / 3 ))" "${buffer[@]}" 3>&1 1>&2 2>&3 || kill -SIGUSR1 "${PROCESS_ID}"); readonly selected_firmware_packages
 fi
-readonly selected_firmware_packages
 
 if whiptail --title "Logging" --yesno "Enable logging?" "${DEFAULT_HEIGHT}" "${DEFAULT_WIDTH}" --defaultno 3>&1 1>&2 2>&3; then
-  echo exec &> >(tee --append "${BASH_SOURCE[0]}.log")
+  exec &> >(tee --append "${BASH_SOURCE[0]}.log")
 fi
 
-set -xue
-
-trap 'printf "%s\n" "Failed to install Arch Linux system"' ERR
+set -ux
 
 if [[ "${disk}" == *nvm* ]]; then
   readonly boot_partition="${disk}p1"
@@ -207,9 +213,8 @@ else
 fi
 cryptsetup --batch-mode luksFormat "${system_partition}" <<- EOF
 	${disk_encryption_password}
-	${disk_encryption_password}
 EOF
-readonly crypt_partition_id="$(uuidgen)"
+crypt_partition_id="$(uuidgen)"; readonly crypt_partition_id
 cryptsetup open "${system_partition}" "${crypt_partition_id}" <<- EOF
 	${disk_encryption_password}
 EOF
@@ -224,11 +229,11 @@ else
   mount "${boot_partition}" /mnt/boot
 fi
 
-function unmount_filesystems() {
+unmount_filesystems() {
   umount --force --recursive --verbose /mnt
   cryptsetup close "${crypt_partition_id}"
 }
-trap 'unmount_filesystems' EXIT
+trap unmount_filesystems EXIT
 
 readonly reflector_options=(
   "--completion-percent" "100.0"
@@ -307,7 +312,7 @@ arch-chroot /mnt locale-gen
 arch-chroot /mnt tee /etc/locale.conf <<- EOF
 	LANG=en_US.UTF-8
 EOF
-arch-chroot /mnt timedatectl set-timezone "${tz}"
+arch-chroot /mnt ln --symbolic --force "/usr/share/zoneinfo/${tz}" /etc/localtime
 
 arch-chroot /mnt mkdir --parents /usr/local/share/kbd/keymaps/
 arch-chroot /mnt tee /usr/local/share/kbd/keymaps/us.map <<- EOF
@@ -366,13 +371,13 @@ arch-chroot /mnt tee "/etc/systemd/network/10-${interface}.network" <<- EOF
 	[DHCP]
 	UseDomains=yes
 EOF
-arch-chroot /mnt systemctl enable systemd-networkd.service
+systemctl --root=/mnt enable systemd-networkd.service
 
 arch-chroot /mnt tee /etc/systemd/timesyncd.conf <<- EOF
 	[Time]
 	NTP=de.pool.ntp.org
 EOF
-arch-chroot /mnt systemctl enable systemd-timesyncd.service
+systemctl --root=/mnt enable systemd-timesyncd.service
 
 arch-chroot /mnt tee /etc/systemd/resolved.conf <<- EOF
 	[Resolve]
@@ -381,17 +386,14 @@ arch-chroot /mnt tee /etc/systemd/resolved.conf <<- EOF
 	LLMNR=no
 	MulticastDNS=no
 EOF
-arch-chroot /mnt systemctl enable systemd-resolved.service
+systemctl --root=/mnt enable systemd-resolved.service
 # Use plain chroot since arch-chroot mounts resolv.conf of the host system
 chroot /mnt ln --symbolic --force /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
 
-arch-chroot /mnt systemctl enable fstrim.timer
+systemctl --root=/mnt enable fstrim.timer
 
 arch-chroot /mnt useradd --create-home --shell /bin/bash "${username}"
-arch-chroot /mnt passwd "${username}" <<- EOF
-	${password}
-	${password}
-EOF
+printf "%s:%s" "${username}" "${password}" | arch-chroot /mnt chpasswd
 arch-chroot /mnt tee "/etc/sudoers.d/${username}" <<- EOF
 	${username} ALL=(ALL) ALL
 EOF
@@ -410,9 +412,11 @@ if [[ "${interface}" == w* ]]; then
 		[General]
 		EnableNetworkConfiguration=false
 	EOF
-  arch-chroot /mnt mkdir --parents --mode=u=rwX,go= /var/lib/iwd/
-  find /var/lib/iwd/ -type f -name "*.psk" -exec cp -- {} /mnt/var/lib/iwd/ \;
-  arch-chroot /mnt systemctl enable iwd.service
+  if [[ -d /var/lib/iwd/ ]]; then
+    arch-chroot /mnt mkdir --parents --mode=u=rwX,go= /var/lib/iwd/
+    find /var/lib/iwd/ -type f -name "*.psk" -exec cp -- {} /mnt/var/lib/iwd/ \;
+  fi
+  systemctl --root=/mnt enable iwd.service
   arch-chroot /mnt usermod --append --groups network "${username}"
 fi
 
@@ -444,12 +448,13 @@ arch-chroot /mnt tee -a /etc/nftables.conf <<- EOF
 	    }
 	}
 EOF
-arch-chroot /mnt systemctl enable nftables.service
+systemctl --root=/mnt enable nftables.service
 
 arch-chroot /mnt tee /etc/ssh/ssh_config <<- EOF
 	HostKeyAlgorithms ssh-ed25519
+	PubkeyAcceptedAlgorithms ssh-ed25519
 
-	KexAlgorithms curve25519-sha256@libssh.org
+	KexAlgorithms mlkem768x25519-sha256
 	Ciphers aes256-gcm@openssh.com
 	MACs hmac-sha2-512-etm@openssh.com
 
@@ -460,7 +465,10 @@ EOF
 arch-chroot /mnt tee /etc/ssh/sshd_config <<- EOF
 	HostKey /etc/ssh/ssh_host_ed25519_key
 
-	KexAlgorithms curve25519-sha256@libssh.org
+	HostKeyAlgorithms ssh-ed25519
+	PubkeyAcceptedAlgorithms ssh-ed25519
+
+	KexAlgorithms mlkem768x25519-sha256
 	Ciphers aes256-gcm@openssh.com
 	MACs hmac-sha2-512-etm@openssh.com
 
@@ -482,7 +490,7 @@ arch-chroot /mnt tee /etc/ssh/sshd_config <<- EOF
 EOF
 
 if [[ "${selection_enable_sshd}" == "yes" ]]; then
-  arch-chroot /mnt systemctl enable sshd.service
+  systemctl --root=/mnt enable sshd.service
 fi
 
 unset microcode
@@ -499,8 +507,8 @@ if [[ "$(< /sys/devices/virtual/dmi/id/sys_vendor)" != "QEMU" ]]; then
   esac
 fi
 
-readonly system_partition_id="$(blkid --match-tag UUID --output value "${system_partition}")"
-readonly virtual_block_device_id="$(blkid --match-tag UUID --output value "${virtual_block_device}")"
+system_partition_id="$(blkid --match-tag UUID --output value "${system_partition}")"; readonly system_partition_id
+virtual_block_device_id="$(blkid --match-tag UUID --output value "${virtual_block_device}")"; readonly virtual_block_device_id
 readonly default_kernel_options=("cryptdevice=UUID=${system_partition_id}:${crypt_partition_id}:allow-discards")
 readonly security_kernel_options=("lockdown=integrity")
 
diff --git a/secure-boot-installation b/secure-boot-installation
--- a/secure-boot-installation
+++ b/secure-boot-installation
@@ -1,23 +1,33 @@
 #!/bin/bash
 
-if ! sudo true; then
+# Installation script for Secure Boot certificates.
+
+error() {
+  printf "%s\n" "Failed to install Secure Boot certificates" >&2
+  exit 1
+}
+
+set -Ee -o pipefail
+
+trap error ERR
+
+sudo --validate
+
+if [[ ! -d /sys/firmware/efi/efivars/ ]]; then
+  printf "%s\n" "UEFI mode required" >&2
   exit 1
 fi
 
-if [[ ! -d /sys/firmware/efi/efivars/ ]]; then
-  printf "UEFI mode required\n"
-  exit 1
-fi
+set -ux
 
 sudo pacman --noconfirm --sync --refresh efitools sbsigntools
 
-readonly GUID="$(uuidgen --random)"
+GUID="$(uuidgen --random)"; readonly GUID
 readonly MICROSOFT_GUID="77fa9abd-0359-4d32-bd60-28f4e78f784b"
 
 temporary_files=()
-trap "{ rm -f \${temporary_files[@]}; }" EXIT
 
-function create_temporary_file() {
+create_temporary_file() {
   local file
 
   file="$(mktemp)"
@@ -25,7 +35,13 @@ function create_temporary_file() {
   printf "%s" "${file}"
 }
 
-function create_certificate() {
+remove_temporary_files() {
+  rm --force "${temporary_files[@]}"
+}
+
+trap remove_temporary_files EXIT
+
+create_certificate() {
   local name="$1"
   local certificate="$2"
   local key="$3"
@@ -33,22 +49,22 @@ function create_certificate() {
   openssl req -newkey rsa:4096 -nodes -keyout "${key}" -new -x509 -sha256 -days 3650 -subj "/CN=${name}" -out "${certificate}" 2> /dev/null
 }
 
-readonly platform_certificate="$(create_temporary_file)"
-readonly platform_key="$(create_temporary_file)"
-readonly platform_signature="$(create_temporary_file)"
-readonly platform_signature_signed="$(create_temporary_file)"
+platform_certificate="$(create_temporary_file)"; readonly platform_certificate
+platform_key="$(create_temporary_file)"; readonly platform_key
+platform_signature="$(create_temporary_file)"; readonly platform_signature
+platform_signature_signed="$(create_temporary_file)"; readonly platform_signature_signed
 create_certificate "Arch Linux Platform Key" "${platform_certificate}" "${platform_key}"
 cert-to-efi-sig-list -g "${GUID}" "${platform_certificate}" "${platform_signature}"
 sign-efi-sig-list -g "${GUID}" -k "${platform_key}" -c "${platform_certificate}" PK "${platform_signature}" "${platform_signature_signed}"
 
 if ! sudo efi-updatevar -f "${platform_signature_signed}" PK; then
-  printf "Failed to update platform key\n"
+  printf "%s\n" "Failed to update platform key" >&2
   exit 1
 fi
 
-readonly unified_kernel_image_certificate="$(create_temporary_file)"
-readonly unified_kernel_image_key="$(create_temporary_file)"
-readonly unified_kernel_image_signature="$(create_temporary_file)"
+unified_kernel_image_certificate="$(create_temporary_file)"; readonly unified_kernel_image_certificate
+unified_kernel_image_key="$(create_temporary_file)"; readonly unified_kernel_image_key
+unified_kernel_image_signature="$(create_temporary_file)"; readonly unified_kernel_image_signature
 create_certificate "Arch Linux Signature Key" "${unified_kernel_image_certificate}" "${unified_kernel_image_key}"
 cert-to-efi-sig-list -g "${GUID}" "${unified_kernel_image_certificate}" "${unified_kernel_image_signature}"
 
@@ -56,11 +72,11 @@ signatures=("${unified_kernel_image_signature}")
 
 read -r -p "Add Microsoft Windows signature? [y/N] "
 if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
-  readonly microsoft_windows_certificate_binary="$(create_temporary_file)"
-  readonly microsoft_windows_certificate="$(create_temporary_file)"
-  readonly microsoft_windows_signature="$(create_temporary_file)"
-  if ! curl -f -L -s "https://go.microsoft.com/fwlink/?linkid=2239776" > "${microsoft_windows_certificate_binary}"; then
-    printf "Failed to download Microsoft Windows Production certificate\n"
+  microsoft_windows_certificate_binary="$(create_temporary_file)"; readonly microsoft_windows_certificate_binary
+  microsoft_windows_certificate="$(create_temporary_file)"; readonly microsoft_windows_certificate
+  microsoft_windows_signature="$(create_temporary_file)"; readonly microsoft_windows_signature
+  if ! curl --fail --location --silent "https://go.microsoft.com/fwlink/?linkid=2239776" > "${microsoft_windows_certificate_binary}"; then
+    printf "%s\n" "Failed to download Microsoft Windows Production certificate" >&2
     exit 1
   fi
   openssl x509 -in "${microsoft_windows_certificate_binary}" -inform DER -out "${microsoft_windows_certificate}" -outform PEM
@@ -70,11 +86,11 @@ fi
 
 read -r -p "Add Microsoft Option ROM signature? [y/N] "
 if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
-  readonly microsoft_option_rom_certificate_binary="$(create_temporary_file)"
-  readonly microsoft_option_rom_certificate="$(create_temporary_file)"
-  readonly microsoft_option_rom_signature="$(create_temporary_file)"
-  if ! curl -f -L -s "https://go.microsoft.com/fwlink/?linkid=2284009" > "${microsoft_option_rom_certificate_binary}"; then
-    printf "Failed to download Microsoft UEFI certificate\n"
+  microsoft_option_rom_certificate_binary="$(create_temporary_file)"; readonly microsoft_option_rom_certificate_binary
+  microsoft_option_rom_certificate="$(create_temporary_file)"; readonly microsoft_option_rom_certificate
+  microsoft_option_rom_signature="$(create_temporary_file)"; readonly microsoft_option_rom_signature
+  if ! curl --fail --location --silent "https://go.microsoft.com/fwlink/?linkid=2284009" > "${microsoft_option_rom_certificate_binary}"; then
+    printf "%s\n" "Failed to download Microsoft Option ROM certificate" >&2
     exit 1
   fi
   openssl x509 -in "${microsoft_option_rom_certificate_binary}" -inform DER -out "${microsoft_option_rom_certificate}" -outform PEM
@@ -82,13 +98,13 @@ if [[ "${REPLY}" =~ ^[Yy]$ ]]; then
   signatures+=("${microsoft_option_rom_signature}")
 fi
 
-readonly all_signatures="$(create_temporary_file)"
-readonly all_signatures_signed="$(create_temporary_file)"
+all_signatures="$(create_temporary_file)"; readonly all_signatures
+all_signatures_signed="$(create_temporary_file)"; readonly all_signatures_signed
 cat "${signatures[@]}" > "${all_signatures}"
 sign-efi-sig-list -g "${GUID}" -k "${platform_key}" -c "${platform_certificate}" db "${all_signatures}" "${all_signatures_signed}"
 
 if ! sudo efi-updatevar -f "${all_signatures_signed}" db; then
-  printf "Failed to update signature database\n"
+  printf "%s\n" "Failed to update signature database" >&2
   exit 1
 fi
 
@@ -97,7 +113,8 @@ readonly secure_boot_key="/etc/secure-boot/db.key"
 sudo mkdir --parents /etc/secure-boot/
 sudo cp "${unified_kernel_image_certificate}" "${secure_boot_certificate}"
 sudo cp "${unified_kernel_image_key}" "${secure_boot_key}"
-sudo chmod u=r,go= "${secure_boot_certificate}" "${secure_boot_key}"
+sudo chmod a=r "${secure_boot_certificate}"
+sudo chmod u=r,go= "${secure_boot_key}"
 
 sudo tee /etc/initcpio/post/sign-unified-kernel-image <<- EOF
 	#!/bin/bash
@@ -109,4 +126,4 @@ sudo tee /etc/initcpio/post/sign-unified-kernel-image <<- EOF
 EOF
 sudo chmod +x /etc/initcpio/post/sign-unified-kernel-image
 
-sudo mkinitcpio -p linux
+sudo mkinitcpio --preset linux
